# Generated by Django 3.1.3 on 2020-11-08 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='Название')),
                ('category', models.TextField(verbose_name='Категория товара')),
                ('url', models.URLField(verbose_name='ссылка на товар')),
                ('image_url', models.URLField(verbose_name='ссылка на картинку')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
    ]
