# Generated by Django 3.1.2 on 2020-11-09 23:12

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('parse', '0002_treecategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treecategory',
            name='category',
            field=models.CharField(max_length=50, unique=True, verbose_name='Категория товара'),
        ),
        migrations.AlterField(
            model_name='treecategory',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='parse.treecategory', verbose_name='Родитель'),
        ),
    ]
