# Generated by Django 3.1.2 on 2020-11-10 05:58

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('parse', '0004_auto_20201110_0848'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='treecategory',
            options={'ordering': ['tree_id', 'level'], 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='parse.treecategory', verbose_name='Категория товара'),
        ),
    ]
