# Generated by Django 3.1.2 on 2020-11-10 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parse', '0008_auto_20201110_0915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treecategory',
            name='category',
            field=models.CharField(max_length=50, verbose_name='Категория товара'),
        ),
    ]
