# Generated by Django 3.1.2 on 2020-11-10 06:19

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('parse', '0009_auto_20201110_0916'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='treecategory',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='parse.treecategory', verbose_name='Категория товара'),
        ),
        migrations.AlterField(
            model_name='treecategory',
            name='category',
            field=models.CharField(max_length=50, unique=True, verbose_name='Категория товара'),
        ),
    ]
