# Generated by Django 3.1.2 on 2020-11-10 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parse', '0012_auto_20201110_0926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.TextField(verbose_name='Категория товара'),
        ),
        migrations.AlterModelTable(
            name='treecategory',
            table='category',
        ),
    ]
