# Generated by Django 3.1.2 on 2020-11-10 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parse', '0014_auto_20201110_0928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.TextField(verbose_name='Категория товара'),
        ),
    ]
